return {
    { "nvim-lua/plenary.nvim", lazy=false, priority=5000}
    "nvim-tree/nvim-tree.lua",
    "nvim-tree/nvim-web-devicons",
    "nvim-telescope/telescope.nvim",
    "folke/tokyonight.nvim",
    "nvim-mini/mini.animate",
    { "ThePrimeagen/harpoon", branch = "harpoon2" },
    "m4xshen/autoclose.nvim",
    { "lervag/vimtex", lazy = false },
    "norcalli/nvim-colorizer.lua",
    "lukas-reineke/indent-blankline.nvim",
    { "saghen/blink.cmp", version = '1.*', lazy = false, enabled = false },
    "neovim/nvim-lspconfig",
    "williamboman/mason.nvim",
    "williamboman/mason-lspconfig.nvim",
    'supermaven-inc/supermaven-nvim',
    "hrsh7th/nvim-cmp",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-path",
    "hrsh7th/cmp-cmdline",
    "f-person/auto-dark-mode.nvim",
    "catppuccin/nvim",
    "gruvbox-community/gruvbox",
    "projekt0n/github-nvim-theme",
}
